sonar.projectKey=Idealy35_medical-bill-api
sonar.organization=idealy35
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**, coverage/**, .eslintrc.js, index.js
sonar.coverage.exclusions=index.js, tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io